// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ysm} from '../models';
import {types} from '../models';

export function AddImportLog(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AnalyzeYSMModel(arg1:string):Promise<ysm.YSMModelMeta>;

export function CheckFileExists(arg1:string):Promise<boolean>;

export function ClearCustomDir(arg1:string):Promise<number>;

export function ClearImportLogs():Promise<void>;

export function CountLinkedModels(arg1:string):Promise<number>;

export function CreateDir(arg1:string):Promise<void>;

export function DeduplicateCustomDir(arg1:string):Promise<number>;

export function DeleteFromRecycle(arg1:string):Promise<void>;

export function EmptyRecycleBin(arg1:string):Promise<number>;

export function ExtractYsmSummary(arg1:string):Promise<ysm.YsmSummary>;

export function GetGlobalCustomDir(arg1:string):Promise<string>;

export function GetImportLogs():Promise<Array<types.ImportLog>>;

export function GetInstanceStatus(arg1:string,arg2:string):Promise<Array<types.InstanceStatus>>;

export function GetLinkMode():Promise<string>;

export function GetMinecraftPath():Promise<string>;

export function GetWindowPosition():Promise<types.WindowState>;

export function HasYSMMod(arg1:string):Promise<boolean>;

export function ImportModelFile(arg1:string,arg2:string):Promise<void>;

export function InstallModelFile(arg1:string,arg2:string):Promise<string>;

export function InstallModelTo(arg1:string,arg2:string):Promise<void>;

export function InstallModelWithOverlay(arg1:string,arg2:string):Promise<string>;

export function IsFileBanned(arg1:string):Promise<boolean>;

export function IsSymlink(arg1:string):Promise<boolean>;

export function ListFileNames(arg1:string):Promise<Array<string>>;

export function ListRecycleBin(arg1:string):Promise<Array<types.ModelEntry>>;

export function ListVersionInstances(arg1:string):Promise<Array<types.VersionInstance>>;

export function LoadAppConfig():Promise<types.AppConfig>;

export function MoveModelFile(arg1:string,arg2:string):Promise<void>;

export function MoveToRecycle(arg1:string):Promise<void>;

export function MoveToRecycleEx(arg1:string):Promise<string|string>;

export function OpenFolder(arg1:string):Promise<void>;

export function RestoreFromRecycle(arg1:string,arg2:string):Promise<void>;

export function SaveAppConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScanCustomModels(arg1:string):Promise<Array<types.ModelEntry>>;

export function ScanModelEntries(arg1:string):Promise<Array<types.ModelEntry>>;

export function SelectDirectory():Promise<string>;

export function SetLinkMode(arg1:string):Promise<void>;

export function SetRepoRoot(arg1:string):Promise<void>;

export function SyncCustomToRepo(arg1:string,arg2:string):Promise<number>;

export function SyncModelToggleStatus(arg1:string,arg2:string):Promise<number>;

export function ToggleModelEnable(arg1:string):Promise<boolean>;
