// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImportLog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddImportLog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AnalyzeYSMModel(arg1) {
  return window['go']['main']['App']['AnalyzeYSMModel'](arg1);
}

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function ClearCustomDir(arg1) {
  return window['go']['main']['App']['ClearCustomDir'](arg1);
}

export function ClearImportLogs() {
  return window['go']['main']['App']['ClearImportLogs']();
}

export function CountLinkedModels(arg1) {
  return window['go']['main']['App']['CountLinkedModels'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function DeduplicateCustomDir(arg1) {
  return window['go']['main']['App']['DeduplicateCustomDir'](arg1);
}

export function DeleteFromRecycle(arg1) {
  return window['go']['main']['App']['DeleteFromRecycle'](arg1);
}

export function EmptyRecycleBin(arg1) {
  return window['go']['main']['App']['EmptyRecycleBin'](arg1);
}

export function ExtractYsmSummary(arg1) {
  return window['go']['main']['App']['ExtractYsmSummary'](arg1);
}

export function GetGlobalCustomDir(arg1) {
  return window['go']['main']['App']['GetGlobalCustomDir'](arg1);
}

export function GetImportLogs() {
  return window['go']['main']['App']['GetImportLogs']();
}

export function GetInstanceStatus(arg1, arg2) {
  return window['go']['main']['App']['GetInstanceStatus'](arg1, arg2);
}

export function GetLinkMode() {
  return window['go']['main']['App']['GetLinkMode']();
}

export function GetMinecraftPath() {
  return window['go']['main']['App']['GetMinecraftPath']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function HasYSMMod(arg1) {
  return window['go']['main']['App']['HasYSMMod'](arg1);
}

export function ImportModelFile(arg1, arg2) {
  return window['go']['main']['App']['ImportModelFile'](arg1, arg2);
}

export function InstallModelFile(arg1, arg2) {
  return window['go']['main']['App']['InstallModelFile'](arg1, arg2);
}

export function InstallModelTo(arg1, arg2) {
  return window['go']['main']['App']['InstallModelTo'](arg1, arg2);
}

export function InstallModelWithOverlay(arg1, arg2) {
  return window['go']['main']['App']['InstallModelWithOverlay'](arg1, arg2);
}

export function IsFileBanned(arg1) {
  return window['go']['main']['App']['IsFileBanned'](arg1);
}

export function IsSymlink(arg1) {
  return window['go']['main']['App']['IsSymlink'](arg1);
}

export function ListFileNames(arg1) {
  return window['go']['main']['App']['ListFileNames'](arg1);
}

export function ListRecycleBin(arg1) {
  return window['go']['main']['App']['ListRecycleBin'](arg1);
}

export function ListVersionInstances(arg1) {
  return window['go']['main']['App']['ListVersionInstances'](arg1);
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function MoveModelFile(arg1, arg2) {
  return window['go']['main']['App']['MoveModelFile'](arg1, arg2);
}

export function MoveToRecycle(arg1) {
  return window['go']['main']['App']['MoveToRecycle'](arg1);
}

export function MoveToRecycleEx(arg1) {
  return window['go']['main']['App']['MoveToRecycleEx'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RestoreFromRecycle(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromRecycle'](arg1, arg2);
}

export function SaveAppConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAppConfig'](arg1, arg2, arg3, arg4);
}

export function SaveWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2, arg3, arg4);
}

export function ScanCustomModels(arg1) {
  return window['go']['main']['App']['ScanCustomModels'](arg1);
}

export function ScanModelEntries(arg1) {
  return window['go']['main']['App']['ScanModelEntries'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetLinkMode(arg1) {
  return window['go']['main']['App']['SetLinkMode'](arg1);
}

export function SetRepoRoot(arg1) {
  return window['go']['main']['App']['SetRepoRoot'](arg1);
}

export function SyncCustomToRepo(arg1, arg2) {
  return window['go']['main']['App']['SyncCustomToRepo'](arg1, arg2);
}

export function SyncModelToggleStatus(arg1, arg2) {
  return window['go']['main']['App']['SyncModelToggleStatus'](arg1, arg2);
}

export function ToggleModelEnable(arg1) {
  return window['go']['main']['App']['ToggleModelEnable'](arg1);
}
