// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {ysm} from '../models';
import {updater} from '../models';
import {main} from '../models';

export function AddImportLog(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AnalyzeBedrockModel(arg1:string):Promise<types.BedrockModel>;

export function AnalyzeYSMModel(arg1:string):Promise<ysm.YSMModelMeta>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function BackupWorkshopCreators():Promise<string>;

export function CancelQueue():Promise<void>;

export function CheckFileExists(arg1:string):Promise<boolean>;

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function ClearCustomDir(arg1:string):Promise<number>;

export function ClearImportLogs():Promise<void>;

export function CountLinkedModels(arg1:string):Promise<number>;

export function CreateDir(arg1:string):Promise<void>;

export function CurrentVersion():Promise<string>;

export function DeduplicateCustomDir(arg1:string):Promise<number>;

export function DeleteFromRecycle(arg1:string):Promise<void>;

export function DownloadFromGitHub(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function EmptyRecycleBin(arg1:string):Promise<number>;

export function EnqueueDownloads(arg1:Array<main.DownloadTask>):Promise<void>;

export function ExportWorkshopCreatorsJSONFile():Promise<string>;

export function ExportWorkshopSitesCSV():Promise<string>;

export function ExportWorkshopSitesJSONFile():Promise<string>;

export function ExtractPreviewTexture(arg1:string):Promise<string>;

export function ExtractYSMHeader(arg1:string):Promise<ysm.YSMHeader>;

export function ExtractYSMHeaderFromBase64(arg1:string):Promise<ysm.YSMHeader>;

export function ExtractYsmSummary(arg1:string):Promise<ysm.YsmSummary>;

export function FindPreviewImage(arg1:string):Promise<string>;

export function GenerateRepoIndex(arg1:string):Promise<string>;

export function GetGlobalCustomDir(arg1:string):Promise<string>;

export function GetImportLogs():Promise<Array<types.ImportLog>>;

export function GetInstanceStatus(arg1:string,arg2:string):Promise<Array<types.InstanceStatus>>;

export function GetLinkMode():Promise<string>;

export function GetMinecraftPath():Promise<string>;

export function GetPackInfo(arg1:string):Promise<types.PackInfo>;

export function GetWindowPosition():Promise<types.WindowState>;

export function HasYSMMod(arg1:string):Promise<boolean>;

export function ImportModelFile(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileOverwrite(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileOverwriteTo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportModelFileSkipCheck(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileTo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportWorkshopSitesCSV(arg1:string):Promise<void>;

export function ImportWorkshopSitesJSONFile():Promise<number>;

export function InstallModelFile(arg1:string,arg2:string):Promise<string>;

export function InstallModelTo(arg1:string,arg2:string):Promise<void>;

export function InstallModelWithOverlay(arg1:string,arg2:string):Promise<string>;

export function IsFileBanned(arg1:string):Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function IsSymlink(arg1:string):Promise<boolean>;

export function ListFileNames(arg1:string):Promise<Array<string>>;

export function ListModelAuthors():Promise<Array<string>>;

export function ListRecycleBin(arg1:string):Promise<Array<types.ModelEntry>>;

export function ListVersionInstances(arg1:string):Promise<Array<types.VersionInstance>>;

export function LoadAppConfig():Promise<types.AppConfig>;

export function LoadWorkshopCreators():Promise<Array<types.WorkshopCreator>>;

export function LoadWorkshopSites():Promise<Array<types.WorkshopSite>>;

export function MergeWorkshopCreatorsFromJSON(arg1:string):Promise<number>;

export function MoveModelFile(arg1:string,arg2:string):Promise<void>;

export function MoveToRecycle(arg1:string):Promise<void>;

export function MoveToRecycleEx(arg1:string):Promise<string|string>;

export function OpenFolder(arg1:string):Promise<void>;

export function QueueStatus():Promise<number|boolean>;

export function RelinkCustomDir(arg1:string,arg2:string):Promise<number>;

export function RemoveDir(arg1:string):Promise<void>;

export function RenameDir(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ReplaceWorkshopCreatorsFromJSON(arg1:string):Promise<number>;

export function ResetWorkshopConfigs():Promise<Array<types.WorkshopSite>>;

export function RestoreFromRecycle(arg1:string,arg2:string):Promise<void>;

export function SaveAppConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SavePreviewTempFile(arg1:string):Promise<string>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveWorkshopCreators(arg1:Array<types.WorkshopCreator>):Promise<void>;

export function SaveWorkshopSites(arg1:Array<types.WorkshopSite>):Promise<void>;

export function ScanCustomModels(arg1:string):Promise<Array<types.ModelEntry>>;

export function ScanModelEntries(arg1:string):Promise<Array<types.ModelEntry>>;

export function SelectDirectory():Promise<string>;

export function SetDownloadMirror(arg1:string):Promise<void>;

export function SetLinkMode(arg1:string):Promise<void>;

export function SetRepoRoot(arg1:string):Promise<void>;

export function StartProxy(arg1:number):Promise<void>;

export function StopProxy():Promise<void>;

export function SyncCustomToRepo(arg1:string,arg2:string):Promise<number>;

export function SyncModelToggleStatus(arg1:string,arg2:string):Promise<number>;

export function ToggleModelEnable(arg1:string):Promise<boolean>;
