// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {ysm} from '../models';
import {updater} from '../models';
import {main} from '../models';

export function AddImportLog(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AnalyzeBedrockModel(arg1:string):Promise<types.BedrockModel>;

export function AnalyzeYSMModel(arg1:string):Promise<ysm.YSMModelMeta>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function BackupWorkshopCreators():Promise<string>;

export function BatchExtractCreatorAvatars():Promise<Record<string, string>>;

export function CachedCreatorAvatar(arg1:string):Promise<string>;

export function CancelQueue():Promise<void>;

export function CheckFileExists(arg1:string):Promise<boolean>;

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function ClearCustomDir(arg1:string):Promise<number>;

export function ClearImportLogs():Promise<void>;

export function ClearInstanceResources(arg1:string,arg2:string):Promise<number>;

export function ClearScanCache():Promise<void>;

export function CopyModelFile(arg1:string,arg2:string):Promise<void>;

export function CountDuplicateFiles(arg1:string):Promise<string>;

export function CountInstanceResources(arg1:string,arg2:string):Promise<number>;

export function CreateDir(arg1:string):Promise<void>;

export function CurrentVersion():Promise<string>;

export function DebugExtractCreatorAvatar(arg1:string):Promise<Record<string, string>>;

export function DeduplicateCustomDir(arg1:string):Promise<number>;

export function DeleteFromRecycle(arg1:string):Promise<void>;

export function DeleteModelDir(arg1:string):Promise<void>;

export function DeleteResourcePack(arg1:string):Promise<void>;

export function DetectResourceType(arg1:string):Promise<string>;

export function DoUpdate(arg1:string,arg2:string):Promise<string>;

export function DownloadFromGitHub(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function EmptyRecycleBin(arg1:string):Promise<number>;

export function EnqueueDownloads(arg1:Array<main.DownloadTask>):Promise<void>;

export function ExportBoneStructures(arg1:string):Promise<string>;

export function ExportModelStructureJSON(arg1:string):Promise<string>;

export function ExportWorkshopCreatorsJSONFile():Promise<string>;

export function ExportWorkshopSitesCSV():Promise<string>;

export function ExportWorkshopSitesJSONFile():Promise<string>;

export function ExtractPreviewTexture(arg1:string):Promise<string>;

export function ExtractYSMHeader(arg1:string):Promise<ysm.YSMHeader>;

export function ExtractYSMHeaderFromBase64(arg1:string):Promise<ysm.YSMHeader>;

export function ExtractYsmSummary(arg1:string):Promise<ysm.YsmSummary>;

export function FindDuplicateFiles(arg1:string):Promise<string>;

export function FindPreviewImage(arg1:string):Promise<string>;

export function GenerateRepoIndex(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetGlobalCustomDir(arg1:string):Promise<string>;

export function GetImportLogs():Promise<Array<types.ImportLog>>;

export function GetInstanceStatus(arg1:string,arg2:string):Promise<Array<types.InstanceStatus>>;

export function GetInstanceSyncStatus(arg1:string):Promise<string>;

export function GetLinkMode():Promise<string>;

export function GetMinecraftPaths():Promise<Array<string>>;

export function GetModel3DSpec(arg1:string):Promise<string>;

export function GetModelTexSizes(arg1:string):Promise<Array<ysm.TexInfo>>;

export function GetPackInfo(arg1:string):Promise<types.PackInfo>;

export function GetRepoRoot(arg1:string):Promise<string>;

export function GetResourceInstanceStatus(arg1:string,arg2:string,arg3:string):Promise<Array<types.InstanceStatus>>;

export function GetSubDirMap():Promise<Record<string, string>>;

export function GetWasmBinary():Promise<Array<number>>;

export function GetWindowPosition():Promise<types.WindowState>;

export function HasYSMMod(arg1:string):Promise<boolean>;

export function ImportByType(arg1:string,arg2:string):Promise<string>;

export function ImportModelFile(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileOverwrite(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileOverwriteTo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportModelFileSkipCheck(arg1:string,arg2:string):Promise<void>;

export function ImportModelFileTo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportResourcePack(arg1:string,arg2:string):Promise<string>;

export function ImportWorkshopSitesCSV(arg1:string):Promise<void>;

export function ImportWorkshopSitesJSONFile():Promise<number>;

export function InstallModelFile(arg1:string,arg2:string):Promise<string>;

export function InstallModelTo(arg1:string,arg2:string):Promise<void>;

export function InstallModelWithOverlay(arg1:string,arg2:string):Promise<string>;

export function InstallResourceToInstance(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InvalidateScanCache():Promise<void>;

export function IsFileBanned(arg1:string):Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function IsResourcePackEnabled(arg1:string):Promise<boolean>;

export function ListAllFilePaths(arg1:string):Promise<Array<string>>;

export function ListFileNames(arg1:string):Promise<Array<string>>;

export function ListModelAuthors():Promise<Array<types.AuthorInfo>>;

export function ListRecycleBin(arg1:string):Promise<Array<types.ModelEntry>>;

export function ListVersionInstances(arg1:string):Promise<Array<types.VersionInstance>>;

export function LoadAppConfig():Promise<types.AppConfig>;

export function LoadGitHubRepos():Promise<Array<types.WorkshopCreator>>;

export function LoadResourceTypes():Promise<string>;

export function LoadWorkshopCreators():Promise<Array<types.WorkshopCreator>>;

export function LoadWorkshopSites():Promise<Array<types.WorkshopSite>>;

export function MergeWorkshopCreatorsFromJSON(arg1:string):Promise<number>;

export function MoveModelFile(arg1:string,arg2:string):Promise<void>;

export function MoveToRecycle(arg1:string):Promise<void>;

export function MoveToRecycleEx(arg1:string):Promise<string|string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInstanceFolder(arg1:string,arg2:string):Promise<void>;

export function PullResourceFromInstance(arg1:string,arg2:string):Promise<number>;

export function PullSingleResourceFromInstance(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PushResourceToInstance(arg1:string,arg2:string):Promise<number>;

export function PushSingleResourceToInstance(arg1:string,arg2:string,arg3:string):Promise<void>;

export function QueueStatus():Promise<number|boolean>;

export function ReadFileBytes(arg1:string):Promise<Array<number>>;

export function ReadPackMeta(arg1:string):Promise<string>;

export function ReadShaderpackLang(arg1:string):Promise<string>;

export function RelinkAllInstanceResources(arg1:string):Promise<number>;

export function RelinkCustomDir(arg1:string,arg2:string):Promise<number>;

export function RemoveDir(arg1:string):Promise<void>;

export function RenameDir(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ReplaceWorkshopCreatorsFromJSON(arg1:string):Promise<number>;

export function ResetResourceRoot(arg1:string):Promise<void>;

export function ResetWorkshopConfigs():Promise<Array<types.WorkshopSite>>;

export function RestartApplication():Promise<void>;

export function RestoreFromRecycle(arg1:string,arg2:string):Promise<void>;

export function SaveAppConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SavePreviewTempFile(arg1:string):Promise<string>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveWorkshopCreators(arg1:Array<types.WorkshopCreator>):Promise<void>;

export function SaveWorkshopCreatorsBySite(arg1:string,arg2:Array<types.WorkshopCreator>):Promise<void>;

export function SaveWorkshopPresetsBySite(arg1:string,arg2:Array<types.WorkshopPresetSearch>):Promise<void>;

export function SaveWorkshopSites(arg1:Array<types.WorkshopSite>):Promise<void>;

export function ScanCustomModels(arg1:string):Promise<Array<types.ModelEntry>>;

export function ScanLocalAuthors():Promise<Array<types.WorkshopCreator>>;

export function ScanModelEntries(arg1:string):Promise<Array<types.ModelEntry>>;

export function SearchModels(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number):Promise<Array<types.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectImportFile(arg1:string,arg2:string):Promise<string>;

export function SelectImportZip():Promise<string>;

export function SetDownloadMirror(arg1:string):Promise<void>;

export function SetLinkMode(arg1:string):Promise<void>;

export function SetRepoRoot(arg1:string):Promise<void>;

export function SetResourceRoot(arg1:string,arg2:string):Promise<void>;

export function StartProxy(arg1:number):Promise<void>;

export function StopProxy():Promise<void>;

export function SyncCustomToRepo(arg1:string,arg2:string):Promise<number>;

export function SyncModelToggleStatus(arg1:string,arg2:string):Promise<number>;

export function SyncResources(arg1:string,arg2:string):Promise<string>;

export function ToggleModelEnable(arg1:string):Promise<boolean>;

export function ToggleResourcePack(arg1:string):Promise<boolean>;

export function ValidateMinecraftDir(arg1:string):Promise<string|string>;
