// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImportLog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddImportLog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AnalyzeBedrockModel(arg1) {
  return window['go']['main']['App']['AnalyzeBedrockModel'](arg1);
}

export function AnalyzeYSMModel(arg1) {
  return window['go']['main']['App']['AnalyzeYSMModel'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BackupWorkshopCreators() {
  return window['go']['main']['App']['BackupWorkshopCreators']();
}

export function BatchExtractCreatorAvatars() {
  return window['go']['main']['App']['BatchExtractCreatorAvatars']();
}

export function CachedCreatorAvatar(arg1) {
  return window['go']['main']['App']['CachedCreatorAvatar'](arg1);
}

export function CancelQueue() {
  return window['go']['main']['App']['CancelQueue']();
}

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCustomDir(arg1) {
  return window['go']['main']['App']['ClearCustomDir'](arg1);
}

export function ClearImportLogs() {
  return window['go']['main']['App']['ClearImportLogs']();
}

export function ClearInstanceResources(arg1) {
  return window['go']['main']['App']['ClearInstanceResources'](arg1);
}

export function CountDuplicateFiles(arg1) {
  return window['go']['main']['App']['CountDuplicateFiles'](arg1);
}

export function CountInstanceResources(arg1) {
  return window['go']['main']['App']['CountInstanceResources'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function DebugExtractCreatorAvatar(arg1) {
  return window['go']['main']['App']['DebugExtractCreatorAvatar'](arg1);
}

export function DeduplicateCustomDir(arg1) {
  return window['go']['main']['App']['DeduplicateCustomDir'](arg1);
}

export function DeleteFromRecycle(arg1) {
  return window['go']['main']['App']['DeleteFromRecycle'](arg1);
}

export function DeleteModelDir(arg1) {
  return window['go']['main']['App']['DeleteModelDir'](arg1);
}

export function DeleteResourcePack(arg1) {
  return window['go']['main']['App']['DeleteResourcePack'](arg1);
}

export function DetectResourceType(arg1) {
  return window['go']['main']['App']['DetectResourceType'](arg1);
}

export function DoUpdate(arg1) {
  return window['go']['main']['App']['DoUpdate'](arg1);
}

export function DownloadFromGitHub(arg1, arg2) {
  return window['go']['main']['App']['DownloadFromGitHub'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function EmptyRecycleBin(arg1) {
  return window['go']['main']['App']['EmptyRecycleBin'](arg1);
}

export function EnqueueDownloads(arg1) {
  return window['go']['main']['App']['EnqueueDownloads'](arg1);
}

export function ExportBoneStructures(arg1) {
  return window['go']['main']['App']['ExportBoneStructures'](arg1);
}

export function ExportModelStructureJSON(arg1) {
  return window['go']['main']['App']['ExportModelStructureJSON'](arg1);
}

export function ExportWorkshopCreatorsJSONFile() {
  return window['go']['main']['App']['ExportWorkshopCreatorsJSONFile']();
}

export function ExportWorkshopSitesCSV() {
  return window['go']['main']['App']['ExportWorkshopSitesCSV']();
}

export function ExportWorkshopSitesJSONFile() {
  return window['go']['main']['App']['ExportWorkshopSitesJSONFile']();
}

export function ExtractPreviewTexture(arg1) {
  return window['go']['main']['App']['ExtractPreviewTexture'](arg1);
}

export function ExtractYSMHeader(arg1) {
  return window['go']['main']['App']['ExtractYSMHeader'](arg1);
}

export function ExtractYSMHeaderFromBase64(arg1) {
  return window['go']['main']['App']['ExtractYSMHeaderFromBase64'](arg1);
}

export function ExtractYsmSummary(arg1) {
  return window['go']['main']['App']['ExtractYsmSummary'](arg1);
}

export function FindDuplicateFiles(arg1) {
  return window['go']['main']['App']['FindDuplicateFiles'](arg1);
}

export function FindPreviewImage(arg1) {
  return window['go']['main']['App']['FindPreviewImage'](arg1);
}

export function GenerateRepoIndex(arg1) {
  return window['go']['main']['App']['GenerateRepoIndex'](arg1);
}

export function GetGlobalCustomDir(arg1) {
  return window['go']['main']['App']['GetGlobalCustomDir'](arg1);
}

export function GetImportLogs() {
  return window['go']['main']['App']['GetImportLogs']();
}

export function GetInstanceStatus(arg1, arg2) {
  return window['go']['main']['App']['GetInstanceStatus'](arg1, arg2);
}

export function GetInstanceSyncStatus(arg1) {
  return window['go']['main']['App']['GetInstanceSyncStatus'](arg1);
}

export function GetLinkMode() {
  return window['go']['main']['App']['GetLinkMode']();
}

export function GetMinecraftPaths() {
  return window['go']['main']['App']['GetMinecraftPaths']();
}

export function GetModel3DSpec(arg1) {
  return window['go']['main']['App']['GetModel3DSpec'](arg1);
}

export function GetModelTexSizes(arg1) {
  return window['go']['main']['App']['GetModelTexSizes'](arg1);
}

export function GetPackInfo(arg1) {
  return window['go']['main']['App']['GetPackInfo'](arg1);
}

export function GetRepoRoot(arg1) {
  return window['go']['main']['App']['GetRepoRoot'](arg1);
}

export function GetResourceInstanceStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResourceInstanceStatus'](arg1, arg2, arg3);
}

export function GetWasmBinary() {
  return window['go']['main']['App']['GetWasmBinary']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function HasYSMMod(arg1) {
  return window['go']['main']['App']['HasYSMMod'](arg1);
}

export function ImportByType(arg1, arg2) {
  return window['go']['main']['App']['ImportByType'](arg1, arg2);
}

export function ImportModelFile(arg1, arg2) {
  return window['go']['main']['App']['ImportModelFile'](arg1, arg2);
}

export function ImportModelFileOverwrite(arg1, arg2) {
  return window['go']['main']['App']['ImportModelFileOverwrite'](arg1, arg2);
}

export function ImportModelFileOverwriteTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportModelFileOverwriteTo'](arg1, arg2, arg3);
}

export function ImportModelFileSkipCheck(arg1, arg2) {
  return window['go']['main']['App']['ImportModelFileSkipCheck'](arg1, arg2);
}

export function ImportModelFileTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportModelFileTo'](arg1, arg2, arg3);
}

export function ImportResourcePack(arg1, arg2) {
  return window['go']['main']['App']['ImportResourcePack'](arg1, arg2);
}

export function ImportWorkshopSitesCSV(arg1) {
  return window['go']['main']['App']['ImportWorkshopSitesCSV'](arg1);
}

export function ImportWorkshopSitesJSONFile() {
  return window['go']['main']['App']['ImportWorkshopSitesJSONFile']();
}

export function InstallModelFile(arg1, arg2) {
  return window['go']['main']['App']['InstallModelFile'](arg1, arg2);
}

export function InstallModelTo(arg1, arg2) {
  return window['go']['main']['App']['InstallModelTo'](arg1, arg2);
}

export function InstallModelWithOverlay(arg1, arg2) {
  return window['go']['main']['App']['InstallModelWithOverlay'](arg1, arg2);
}

export function InstallResourceToInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallResourceToInstance'](arg1, arg2, arg3);
}

export function InvalidateScanCache() {
  return window['go']['main']['App']['InvalidateScanCache']();
}

export function IsFileBanned(arg1) {
  return window['go']['main']['App']['IsFileBanned'](arg1);
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function IsResourcePackEnabled(arg1) {
  return window['go']['main']['App']['IsResourcePackEnabled'](arg1);
}

export function ListFileNames(arg1) {
  return window['go']['main']['App']['ListFileNames'](arg1);
}

export function ListModelAuthors() {
  return window['go']['main']['App']['ListModelAuthors']();
}

export function ListRecycleBin(arg1) {
  return window['go']['main']['App']['ListRecycleBin'](arg1);
}

export function ListVersionInstances(arg1) {
  return window['go']['main']['App']['ListVersionInstances'](arg1);
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function LoadGitHubRepos() {
  return window['go']['main']['App']['LoadGitHubRepos']();
}

export function LoadResourceTypes() {
  return window['go']['main']['App']['LoadResourceTypes']();
}

export function LoadWorkshopCreators() {
  return window['go']['main']['App']['LoadWorkshopCreators']();
}

export function LoadWorkshopSites() {
  return window['go']['main']['App']['LoadWorkshopSites']();
}

export function MergeWorkshopCreatorsFromJSON(arg1) {
  return window['go']['main']['App']['MergeWorkshopCreatorsFromJSON'](arg1);
}

export function MoveModelFile(arg1, arg2) {
  return window['go']['main']['App']['MoveModelFile'](arg1, arg2);
}

export function MoveToRecycle(arg1) {
  return window['go']['main']['App']['MoveToRecycle'](arg1);
}

export function MoveToRecycleEx(arg1) {
  return window['go']['main']['App']['MoveToRecycleEx'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PullResourceFromInstance(arg1, arg2) {
  return window['go']['main']['App']['PullResourceFromInstance'](arg1, arg2);
}

export function PullSingleResourceFromInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullSingleResourceFromInstance'](arg1, arg2, arg3);
}

export function PushResourceToInstance(arg1, arg2) {
  return window['go']['main']['App']['PushResourceToInstance'](arg1, arg2);
}

export function PushSingleResourceToInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushSingleResourceToInstance'](arg1, arg2, arg3);
}

export function QueueStatus() {
  return window['go']['main']['App']['QueueStatus']();
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}

export function ReadPackMeta(arg1) {
  return window['go']['main']['App']['ReadPackMeta'](arg1);
}

export function ReadShaderpackLang(arg1) {
  return window['go']['main']['App']['ReadShaderpackLang'](arg1);
}

export function RelinkAllInstanceResources(arg1) {
  return window['go']['main']['App']['RelinkAllInstanceResources'](arg1);
}

export function RelinkCustomDir(arg1, arg2) {
  return window['go']['main']['App']['RelinkCustomDir'](arg1, arg2);
}

export function RemoveDir(arg1) {
  return window['go']['main']['App']['RemoveDir'](arg1);
}

export function RenameDir(arg1, arg2) {
  return window['go']['main']['App']['RenameDir'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ReplaceWorkshopCreatorsFromJSON(arg1) {
  return window['go']['main']['App']['ReplaceWorkshopCreatorsFromJSON'](arg1);
}

export function ResetResourceRoot(arg1) {
  return window['go']['main']['App']['ResetResourceRoot'](arg1);
}

export function ResetWorkshopConfigs() {
  return window['go']['main']['App']['ResetWorkshopConfigs']();
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function RestoreFromRecycle(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromRecycle'](arg1, arg2);
}

export function SaveAppConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveAppConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SavePreviewTempFile(arg1) {
  return window['go']['main']['App']['SavePreviewTempFile'](arg1);
}

export function SaveWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2, arg3, arg4);
}

export function SaveWorkshopCreators(arg1) {
  return window['go']['main']['App']['SaveWorkshopCreators'](arg1);
}

export function SaveWorkshopCreatorsBySite(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkshopCreatorsBySite'](arg1, arg2);
}

export function SaveWorkshopPresetsBySite(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkshopPresetsBySite'](arg1, arg2);
}

export function SaveWorkshopSites(arg1) {
  return window['go']['main']['App']['SaveWorkshopSites'](arg1);
}

export function ScanCustomModels(arg1) {
  return window['go']['main']['App']['ScanCustomModels'](arg1);
}

export function ScanLocalAuthors() {
  return window['go']['main']['App']['ScanLocalAuthors']();
}

export function ScanModelEntries(arg1) {
  return window['go']['main']['App']['ScanModelEntries'](arg1);
}

export function SearchModels(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SearchModels'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImportFile(arg1, arg2) {
  return window['go']['main']['App']['SelectImportFile'](arg1, arg2);
}

export function SelectImportZip() {
  return window['go']['main']['App']['SelectImportZip']();
}

export function SetDownloadMirror(arg1) {
  return window['go']['main']['App']['SetDownloadMirror'](arg1);
}

export function SetLinkMode(arg1) {
  return window['go']['main']['App']['SetLinkMode'](arg1);
}

export function SetRepoRoot(arg1) {
  return window['go']['main']['App']['SetRepoRoot'](arg1);
}

export function SetResourceRoot(arg1, arg2) {
  return window['go']['main']['App']['SetResourceRoot'](arg1, arg2);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function SyncCustomToRepo(arg1, arg2) {
  return window['go']['main']['App']['SyncCustomToRepo'](arg1, arg2);
}

export function SyncModelToggleStatus(arg1, arg2) {
  return window['go']['main']['App']['SyncModelToggleStatus'](arg1, arg2);
}

export function SyncResources(arg1, arg2) {
  return window['go']['main']['App']['SyncResources'](arg1, arg2);
}

export function ToggleModelEnable(arg1) {
  return window['go']['main']['App']['ToggleModelEnable'](arg1);
}

export function ToggleResourcePack(arg1) {
  return window['go']['main']['App']['ToggleResourcePack'](arg1);
}

export function ValidateMinecraftDir(arg1) {
  return window['go']['main']['App']['ValidateMinecraftDir'](arg1);
}
